-- MySQL Script generated by MySQL Workbench
-- 05/16/16 14:29:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mywallet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mywallet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mywallet` DEFAULT CHARACTER SET utf8 ;
USE `mywallet` ;

-- -----------------------------------------------------
-- Table `mywallet`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mywallet`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(256) NULL,
  `name` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `login` (`id` ASC, `password` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mywallet`.`wallets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mywallet`.`wallets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_wallets_users1_idx` (`user_id` ASC),
  INDEX `search` (`id` ASC, `user_id` ASC),
  UNIQUE INDEX `autocomplete` (`user_id` ASC, `name` ASC),
  CONSTRAINT `fk_wallets_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mywallet`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mywallet`.`lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mywallet`.`lists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_lists_users1_idx` (`user_id` ASC),
  INDEX `search` (`id` ASC, `user_id` ASC),
  UNIQUE INDEX `autocomplete` (`name` ASC, `user_id` ASC),
  CONSTRAINT `fk_lists_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mywallet`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mywallet`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mywallet`.`transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `wallet_id` INT NOT NULL,
  `list_id` INT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ammount` FLOAT(4) NULL,
  `description` VARCHAR(250) NULL,
  PRIMARY KEY (`id`, `user_id`, `wallet_id`),
  INDEX `fk_transactions_wallets_idx` (`wallet_id` ASC),
  INDEX `fk_transactions_lists1_idx` (`list_id` ASC),
  INDEX `fk_transactions_users1_idx` (`user_id` ASC),
  INDEX `search_list` (`user_id` ASC, `wallet_id` ASC, `list_id` ASC, `date` ASC),
  CONSTRAINT `fk_transactions_wallets`
    FOREIGN KEY (`wallet_id`)
    REFERENCES `mywallet`.`wallets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_lists1`
    FOREIGN KEY (`list_id`)
    REFERENCES `mywallet`.`lists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mywallet`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mywallet`.`auth_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mywallet`.`auth_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mywallet`.`auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mywallet`.`auth` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auth_type_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `email` VARCHAR(75) NULL,
  `is_primary` TINYINT(1) NULL DEFAULT 0,
  `auth_key` VARCHAR(256) NULL,
  `auth_token` VARCHAR(256) NULL,
  PRIMARY KEY (`id`, `auth_type_id`, `user_id`),
  INDEX `fk_auth_users1_idx` (`user_id` ASC),
  INDEX `fk_auth_auth_types1_idx` (`auth_type_id` ASC),
  INDEX `login` (`user_id` ASC, `auth_type_id` ASC, `email` ASC),
  INDEX `foregin_login` (`auth_key` ASC, `auth_token` ASC, `email` ASC, `auth_type_id` ASC),
  INDEX `list` (`is_primary` ASC, `user_id` ASC, `auth_type_id` ASC),
  UNIQUE INDEX `single_auth` (`auth_type_id` ASC, `email` ASC),
  CONSTRAINT `fk_auth_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mywallet`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auth_auth_types1`
    FOREIGN KEY (`auth_type_id`)
    REFERENCES `mywallet`.`auth_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
